"use client"
import Header from "@/components/Header"
import useSWRInfinite from "swr/infinite"
import Intersection from "@/components/Intersection"
import AddTweet from "@/components/AddTweet"
import Tweet from "@/components/Tweet"

// export const metadata = {
//   title: "Explore",
//   description: "Generated by create next app",
// }

const getKey = (pageIndex: number, previousPageData: any) => {
  if (previousPageData && !previousPageData.length) return null // reached the end
  return `/api/tweets/explore?page=${pageIndex}` // SWR key
}

export default function Page() {
  const { data, size, setSize, isLoading } = useSWRInfinite(getKey, (...args) =>
    fetch(...args).then((res) => res.json())
  )
  if (!data) return "loading"

  return (
    <div className="flex-1">
      <Header title={"explore"} />

      <AddTweet />
      <div className="flex flex-col overflow-y-scroll">
        {isLoading && <div>Loading</div>}
        {data.map((tweets) => {
          return tweets.map((tweet: any) => (
            <Tweet key={tweet.id} tweet={tweet} />
          ))
        })}
      </div>

      <Intersection callback={() => setSize(size + 1)}>
        <button
          className="m-10 mx-auto px-6 py-2 bg-blue-500 w-min rounded-full whitespace-nowrap"
          onClick={() => setSize(size + 1)}
        >
          Load more
        </button>
      </Intersection>
    </div>
  )
}
