import Header from "@/components/Header"

export const metadata = {
  title: "Explore",
  description: "Generated by create next app",
}

export default function Page() {
  return (
    <>
      <Header title={metadata.title} />
    </>
  )
}
