"use client"
import Header from "@/components/Header"
import useSWR from "swr"
import { useState } from "react"
import Tweet from "@/components/Tweet"
import useSWRInfinite from "swr/infinite"

// export const metadata = {
//   title: "Explore",
//   description: "Generated by create next app",
// }

const getKey = (pageIndex: number, previousPageData: any) => {
  if (previousPageData && !previousPageData.length) return null // reached the end
  return `/api/tweets/explore?page=${pageIndex}` // SWR key
}

export default function Page() {
  const { data, size, setSize } = useSWRInfinite(getKey, (...args) =>
    fetch(...args).then((res) => res.json())
  )
  if (!data) return "loading"

  return (
    <>
      <Header title={"explore"} />
      {data.map((tweets, index) => {
        console.log({ tweets }, { size })
        return tweets.map((tweet: any) => (
          <Tweet key={tweet.id} tweet={tweet} />
        ))
      })}
      <button
        className="m-10 mx-auto px-6 py-2 bg-blue-500 w-min rounded-full whitespace-nowrap"
        onClick={() => setSize(size + 1)}
      >
        Load more
      </button>
    </>
  )
}
