import { SignedOut } from "@clerk/nextjs"
import SignBar from "@/components/SignBar"
import AddTweet from "@/components/AddTweet"
import Header from "@/components/Header"

async function getTweets() {
  const response = await fetch("http://localhost:3000/api/tweets/")
  if (!response.ok) return new Error("Error during fetching")
  const { tweets } = await response.json()
  console.log(tweets)
  return tweets
}

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
}

export default async function Home() {
  const data = await getTweets()

  // {data.length && data.map((tweet: any) => <Post key={tweet.id} />)}
  return (
    <>
      <Header title={metadata.title} />
      <SignedOut>
        <SignBar />
      </SignedOut>
      <AddTweet />
    </>
  )
}
